# Generated by Django 5.0.6 on 2024-06-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
