# Generated by Django 5.0.6 on 2024-06-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0004_usercombineddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserCombinedData',
        ),
    ]
