# Generated by Django 5.0.6 on 2024-06-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0006_rename_birthdate_userprofile_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAppInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
